// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationHandler.Models;

#nullable disable

namespace MigrationHandler.Migrations
{
    [DbContext(typeof(MigrationHandlerDbContext))]
    [Migration("20230222185405_DeletePostAndBlogs")]
    partial class DeletePostAndBlogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");
#pragma warning restore 612, 618
        }
    }
}
